### ISSUE TITLE
Weltenmenü. Regeln neben Weltenbutton.

### ISSUE THREAD

**Issue by Jonxyzas** [iAmCriptic/tuerstehergame#13]
Die buttons mit den jeweiligen regeln soll neben die butten die zu den welten führen angeordnet sein.

**Comment by iAmCriptic** [comment]
Außerdem noch anpassung, damit man entweder scrollen oder alle welten sehen kann bitte auch

**Comment by iAmCriptic** [comment]
Also Man hat nen weltenmenü jetzt, allerdings geht es mit dem scrollen noch nicht. weiß aber nicht ob wir es brauchen

**Comment by iAmCriptic** [comment]
Wir lassen das scrollen erstmal raus und starten mit 3 Leveln.
